### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by dbalatero**
I think the docs meant to say `without` here, not `with`? Let me know if that's wrong though!

### CODE REVIEW

**Comment by loreto** [comment]
@mohsenari This change is going to get obliterated since we publish this repo from our opensource monorepo.

@dbalatero Due to a quirk in our internal setup, we need to take PRs for this project in our opensource monorepo and then it will be published here automatically. Do you mind re-opening the PR against this file instead https://github.com/jetpack-io/opensource/blob/main/typeid/typeid-js/README.md

Thanks so much (I could do it too if you prefer, but I think it'd be cool if you get recognized as a contributor by Github)

**Comment by mohsenari** [comment]
@loreto ah I forgot about monorepo. my bad

**Comment by dbalatero** [comment]
@loreto no problem, but you should add a `.github/PULL_REQUEST_TEMPLATE.md` file in every generated repo that warns people to only commit to the monorepo:

> ⚠️ ⚠️ ⚠️ This repo is auto-generated from our monorepo. Please open your PRs there.

And hot link them to the right spot?

**Comment by loreto** [comment]
> @loreto no problem, but you should add a `.github/PULL_REQUEST_TEMPLATE.md` file in every generated repo that warns people to only commit to the monorepo:
> 
> > ⚠️ ⚠️ ⚠️ This repo is auto-generated from our monorepo. Please open your PRs there.
> 
> And hot link them to the right spot?

Ah, that's a good idea! I mention the opensource monorepo in the CONTRIBUTING file, but your idea is better and would be much more visible. I'll add that.

**Comment by dbalatero** [comment]
No one reads readmes ;)

**Pull request merged**
